#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jsonpatch
Version  : 1.24
Release  : 38
URL      : https://files.pythonhosted.org/packages/30/ac/9b6478a560627e4310130a9e35c31a9f4d650704bbd03946e77c73abcf6c/jsonpatch-1.24.tar.gz
Source0  : https://files.pythonhosted.org/packages/30/ac/9b6478a560627e4310130a9e35c31a9f4d650704bbd03946e77c73abcf6c/jsonpatch-1.24.tar.gz
Summary  : Apply JSON-Patches (RFC 6902)
Group    : Development/Tools
License  : BSD-3-Clause
Requires: jsonpatch-bin = %{version}-%{release}
Requires: jsonpatch-license = %{version}-%{release}
Requires: jsonpatch-python = %{version}-%{release}
Requires: jsonpatch-python3 = %{version}-%{release}
Requires: jsonpointer
BuildRequires : buildreq-distutils3
BuildRequires : jsonpointer

%description
python-json-patch
=================
[![PyPI version](https://img.shields.io/pypi/v/jsonpatch.svg)](https://pypi.python.org/pypi/jsonpatch/)
[![Supported Python versions](https://img.shields.io/pypi/pyversions/jsonpatch.svg)](https://pypi.python.org/pypi/jsonpatch/)
[![Build Status](https://travis-ci.org/stefankoegl/python-json-patch.png?branch=master)](https://travis-ci.org/stefankoegl/python-json-patch)
[![Coverage Status](https://coveralls.io/repos/stefankoegl/python-json-patch/badge.png?branch=master)](https://coveralls.io/r/stefankoegl/python-json-patch?branch=master)

%package bin
Summary: bin components for the jsonpatch package.
Group: Binaries
Requires: jsonpatch-license = %{version}-%{release}

%description bin
bin components for the jsonpatch package.


%package license
Summary: license components for the jsonpatch package.
Group: Default

%description license
license components for the jsonpatch package.


%package python
Summary: python components for the jsonpatch package.
Group: Default
Requires: jsonpatch-python3 = %{version}-%{release}

%description python
python components for the jsonpatch package.


%package python3
Summary: python3 components for the jsonpatch package.
Group: Default
Requires: python3-core

%description python3
python3 components for the jsonpatch package.


%prep
%setup -q -n jsonpatch-1.24

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1564414727
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python tests.py
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/jsonpatch
cp COPYING %{buildroot}/usr/share/package-licenses/jsonpatch/COPYING
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/jsondiff
/usr/bin/jsonpatch

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/jsonpatch/COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
